Repository dao-doers/dao-frontend, pull requests merged in 2022-01, with the labels that each got.

#1 fix-redux
  redux/slices/proposals.ts
  redux/slices/votes.ts
Labels: Review needed

#4 [NEW-16] Filters in sidebar
  components/DAOPlainButton/DAOPlainButton.tsx
  components/DesktopMenu/DesktopMenu.tsx
  components/MenuContent/MenuContent.tsx
  components/MobileMenu/MobileMenu.tsx
  enums/proposalStatus.ts
  pages/_document.tsx
  pages/index.tsx
  public/favicon.ico
  public/favicon.png
  public/vercel.svg
  redux/slices/proposals.ts
  sections/newPage/NewFundingForm/NewFundingForm.tsx
  sections/newPage/NewProposalForm/NewProposalForm.tsx
Labels: Problem

#2 [NEW-05] & [NEW-20] Improve indexer status checking method and UI & Update indexer every 30 secs
  .eslintrc.json
  .gitignore
  components/BlockchainStatus/BlockchainStatus.tsx
  components/DAOTile/DAOTile.tsx
  config/config.ts
  enums/daoTileVariants.ts
  hooks/useCheckIndexerStatus.ts
  hooks/useGuildKick.ts
  pages/index.tsx
  pages/new.tsx
  pages/proposal/[id].tsx
  sections/homePage/ProposalTile/ProposalTile.tsx
  sections/homePage/VoteTile/VoteTile.tsx
  sections/newPage/GuildKickForm/GuildKickForm.tsx
  sections/newPage/NewFundingForm/NewFundingForm.tsx
  sections/newPage/NewProposalForm/NewProposalForm.tsx
  theme/theme.ts
  types/common/ChainAddress.ts
  types/common/ChartCommons.ts
  types/common/Contract.ts
  types/common/Contracts.ts
  types/index.ts
  types/schema.ts
  types/swap/SwapCharts.ts
  types/swap/SwapInfo.ts
  types/swap/SwapLiquidityPool.ts
  types/swap/SwapMain.ts
  types/swap/SwapParameters.ts
  types/swap/SwapPlatform.ts
  types/swap/SwapTargets.ts
  types/swap/SwapToken.ts
  types/swap/SwapTokensList.ts
  utils/login.ts
  utils/routes.ts
Labels: Review needed

#5 [NEW-02] Display balance of dCKB and shares in out app
  .env.development
  .env.production
  abi/ERC20.json
  components/BlockchainStatus/BlockchainStatus.tsx
  hooks/useCheckBalance.ts
  hooks/useERC20Contract.ts
  next.config.js
  package.json
  pages/index.tsx
  redux/slices/proposals.ts
  utils/formatShannons.ts
  utils/login.ts
  yarn.lock
Labels: To merge, Review needed

#3 [NEW-14] Handle Processing proposal after Grace period
  components/BlockchainStatus/BlockchainStatus.tsx
  components/MenuContent/MenuContent.tsx
  enums/proposalStatus.ts
  hooks/useProcessProposal.ts
  redux/slices/proposals.ts
  sections/homePage/VoteChart/VoteChart.tsx
  sections/homePage/VoteSection/VoteSection.tsx
  theme/theme.ts
Labels: To merge, Review needed

#12 Login improvement
  components/BlockchainStatus/BlockchainStatus.tsx
  components/ConnectWalletButton/ConnectWalletButton.tsx
  components/Layout/Layout.tsx
  hooks/useMaintainSession.ts
  pages/_app.tsx
  pages/index.tsx
  utils/login.ts
Labels: Review needed
